import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const downloadFullPlanPDF = (plan) => {
  if (!plan) {
    alert("No plan data available!");
    return;
  }

  const doc = new jsPDF();
  let y = 20;

  doc.setFontSize(22);
  doc.text("🏋️ Personalized Fitness Plan", 14, y);
  y += 10;

  // ======= Tips =======
  doc.setFontSize(16);
  doc.text("💡 Fitness Tips", 14, y);
  y += 6;
  doc.setFontSize(11);

  plan.tips.forEach((tip, i) => {
    doc.text(`• ${tip}`, 14, y);
    y += 6;
    if (y > 270) {
      doc.addPage();
      y = 20;
    }
  });

  y += 10;

  // ======= Diet Plan =======
  doc.setFontSize(16);
  doc.text("🍽️ Diet Plan", 14, y);
  y += 6;

  const dietRows = plan.diet_plan.map((meal) => [
    meal.meal_time,
    meal.food_item.join(", "),
    meal["purpose/benefits"],
  ]);

  autoTable(doc, {
    head: [["Meal Time", "Food Items", "Purpose / Benefits"]],
    body: dietRows,
    startY: y,
    styles: { fontSize: 9, cellPadding: 3 },
    headStyles: { fillColor: [255, 159, 64], textColor: [255, 255, 255] },
  });

  y = doc.lastAutoTable.finalY + 10;

  // ======= Workout Plan =======
  doc.setFontSize(16);
  doc.text("💪 Workout Plan", 14, y);
  y += 6;

  plan.workout_plan.forEach((day) => {
    if (y > 260) {
      doc.addPage();
      y = 20;
    }

    doc.setFontSize(13);
    doc.text(`${day.day} — ${day.focus}`, 14, y);
    y += 5;

    if (day.exercises.length === 0) {
      doc.setFontSize(10);
      doc.text("Rest Day 💤", 16, y);
      y += 6;
    } else {
      const exerciseRows = day.exercises.map((ex) => [
        ex.name,
        ex.sets,
        ex.reps,
      ]);

      autoTable(doc, {
        head: [["Exercise", "Sets", "Reps"]],
        body: exerciseRows,
        startY: y,
        styles: { fontSize: 9, cellPadding: 2 },
        headStyles: { fillColor: [76, 175, 80], textColor: [255, 255, 255] },
        margin: { left: 14 },
      });

      y = doc.lastAutoTable.finalY + 8;
    }
  });

  // ======= Footer =======
  doc.setFontSize(10);
  doc.text("Generated by Noice Fitness Planner 💙", 14, 290);

  doc.save("Fitness_Plan.pdf");
};
